stages:
  - build-base
  - build
  - acceptance

build-base-image-latest:
  image: docker:20.10.16
  stage: build-base
  services:
  - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile.base -t $CI_REGISTRY_IMAGE/base:latest .
    - docker push $CI_REGISTRY_IMAGE/base:latest
  only:
    - master

# https://docs.gitlab.com/ee/user/packages/container_registry/index.html#build-and-push-by-using-gitlab-cicd
build-image-ru-latest:
  image: docker:20.10.16
  when: manual
  stage: build
  services:
  - docker:20.10.16-dind
  variables:
    LANG: ru
    # https://spacy.io/models/ru#ru_core_news_md  dim = 300
    MODEL: ru_core_news_md
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg NLP_MODEL=$MODEL -t $CI_REGISTRY_IMAGE/$LANG:latest .
    - docker push $CI_REGISTRY_IMAGE/$LANG:latest
  only:
    - master

build-image-en-latest:
  image: docker:20.10.16
  when: manual
  stage: build
  services:
  - docker:20.10.16-dind
  variables:
    LANG: en
    # https://spacy.io/models/en#en_core_web_md
    MODEL: en_core_web_md
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg NLP_MODEL=$MODEL -t $CI_REGISTRY_IMAGE/$LANG:latest .
    - docker push $CI_REGISTRY_IMAGE/$LANG:latest
  only:
    - master

build-image-pl-latest:
  image: docker:20.10.16
  when: manual
  stage: build
  services:
  - docker:20.10.16-dind
  variables:
    LANG: pl
    # https://spacy.io/models/en#en_core_web_md
    MODEL: pl_core_news_md
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg NLP_MODEL=$MODEL -t $CI_REGISTRY_IMAGE/$LANG:latest .
    - docker push $CI_REGISTRY_IMAGE/$LANG:latest
  only:
    - master

# ======================= acceptance ==============================
test-image-ru:
  image: $CI_REGISTRY_IMAGE/base:latest
  when: manual
  stage: acceptance
  variables:
    LANG: ru
  services:
    - name: $CI_REGISTRY_IMAGE/$LANG:latest
      alias: text-to-vec-ru
  script:
    - |
      GRPC_DNS_RESOLVER=native TEXT_TO_VECTOR_SERVICE=text-to-vec-$LANG:50051 \
          python tester-client.py dim=300 min_similarity=0.75 "Когда планируется день открытых дверей?" \
          "В какой день пройдет день открытых дверей?"
  only:
    - master

test-image-en:
  image: $CI_REGISTRY_IMAGE/base:latest
  when: manual
  stage: acceptance
  variables:
    LANG: en
  services:
    - name: $CI_REGISTRY_IMAGE/$LANG:latest
      alias: text-to-vec-en
  script:
    - |
      GRPC_DNS_RESOLVER=native TEXT_TO_VECTOR_SERVICE=text-to-vec-$LANG:50051 \
          python tester-client.py dim=300 min_similarity=0.71 "how old are you?" \
          "what is your age?"
  only:
    - master

test-image-pl:
  image: $CI_REGISTRY_IMAGE/base:latest
  when: manual
  stage: acceptance
  variables:
    LANG: pl
  services:
    - name: $CI_REGISTRY_IMAGE/$LANG:latest
      alias: text-to-vec-pl
  script:
    - |
      GRPC_DNS_RESOLVER=native TEXT_TO_VECTOR_SERVICE=text-to-vec-$LANG:50051 \
          python tester-client.py dim=300 min_similarity=0.68 \
          "które miasto jest najlepsze?" "gdzie jest najlepsze miejsce do życia?"
  only:
    - master