# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import text_to_vector_pb2 as text__to__vector__pb2


class TextToVectorStub(object):
    """Accepts text and transforms it to vector in word embedding space using nlp model server is started with
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transform = channel.unary_unary(
                '/TextToVector/Transform',
                request_serializer=text__to__vector__pb2.Text.SerializeToString,
                response_deserializer=text__to__vector__pb2.Vector.FromString,
                )


class TextToVectorServicer(object):
    """Accepts text and transforms it to vector in word embedding space using nlp model server is started with
    """

    def Transform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToVectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transform': grpc.unary_unary_rpc_method_handler(
                    servicer.Transform,
                    request_deserializer=text__to__vector__pb2.Text.FromString,
                    response_serializer=text__to__vector__pb2.Vector.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TextToVector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextToVector(object):
    """Accepts text and transforms it to vector in word embedding space using nlp model server is started with
    """

    @staticmethod
    def Transform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TextToVector/Transform',
            text__to__vector__pb2.Text.SerializeToString,
            text__to__vector__pb2.Vector.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
