# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_to_vector.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14text_to_vector.proto\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x18\n\x06Vector\x12\x0e\n\x06vector\x18\x01 \x03(\x01\x32+\n\x0cTextToVector\x12\x1b\n\tTransform\x12\x05.Text\x1a\x07.Vectorb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_to_vector_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXT._serialized_start=24
  _TEXT._serialized_end=44
  _VECTOR._serialized_start=46
  _VECTOR._serialized_end=70
  _TEXTTOVECTOR._serialized_start=72
  _TEXTTOVECTOR._serialized_end=115
# @@protoc_insertion_point(module_scope)
